PROJECT_ARTIFACTS_DIR ?= $(ARTIFACTS_ROOT)
DOCS_SITE_DIR ?= $(ARTIFACTS_ROOT)/root/docs/site
DOCS_BUILD_SITE_DIR ?= $(DOCS_SITE_DIR)
DOCS_CHECK_SITE_DIR ?= $(DOCS_SITE_DIR)
DOCS_SERVE_SITE_DIR ?= $(DOCS_SITE_DIR)
DOCS_CACHE_DIR ?= $(ARTIFACTS_ROOT)/root/docs/.cache
DOCS_BUILD_CONFIG_FILE ?= $(MKDOCS_CFG)
DOCS_CHECK_CONFIG_FILE ?= $(MKDOCS_CFG)
DOCS_SERVE_CONFIG_FILE ?= $(MKDOCS_CFG)
DOCS_BUILD_PREPARE_TARGETS :=
DOCS_CHECK_PREPARE_TARGETS :=
DOCS_SERVE_PREPARE_TARGETS :=
MKDOCS_LOCAL_SITE_URL ?= http://127.0.0.1:8000/
DOCS_DEV_ADDR ?= 127.0.0.1:8000
DOCS_SERVE_SITE_URL ?= $(MKDOCS_LOCAL_SITE_URL)
DOCS_BUILD_ENV ?= NO_MKDOCS_2_WARNING=true
DOCS_CHECK_ENV ?= NO_MKDOCS_2_WARNING=true
DOCS_SERVE_ENV ?= NO_MKDOCS_2_WARNING=true

include $(abspath $(dir $(lastword $(MAKEFILE_LIST))))/bijux-py/docs.mk
