from __future__ import annotations

from .project import ATLAS_DEFAULTS, DATA_DEFAULTS, PROJECT_PATHS


DEFAULT_AADR_VERSION = DATA_DEFAULTS.aadr_version
DEFAULT_ATLAS_SLUG = ATLAS_DEFAULTS.slug
DEFAULT_ATLAS_TITLE = ATLAS_DEFAULTS.title
DEFAULT_PUBLISHED_COUNTRIES = ATLAS_DEFAULTS.published_countries
NORDIC_BBOX = DATA_DEFAULTS.nordic_bbox
DEFAULT_DATA_ROOT = PROJECT_PATHS.data_root
DEFAULT_AADR_ROOT = PROJECT_PATHS.aadr_root
DEFAULT_REPORT_ROOT = PROJECT_PATHS.report_root
DEFAULT_CONTEXT_ROOT = PROJECT_PATHS.context_root
