[mypy]
python_version = 3.11
strict = true
pretty = true
show_error_codes = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
namespace_packages = true
plugins = pydantic.mypy
mypy_path = packages/bijux-pollenomics/src:packages/bijux-pollenomics-dev/src
files = packages/bijux-pollenomics/src, packages/bijux-pollenomics/tests, packages/bijux-pollenomics-dev/src, packages/bijux-pollenomics-dev/tests
exclude = ^(\.venv|build|dist|docs|htmlcov|\.mypy_cache|\.pytest_cache|\.ruff_cache|\.tox|__pycache__|migrations|\.egg-info|node_modules|artifacts|site)/

[pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
