target-version = "py311"
line-length = 88
respect-gitignore = true
cache-dir = "artifacts/root/ruff-cache"
src = [
  "packages/bijux-pollenomics/src",
  "packages/bijux-pollenomics/tests",
  "packages/bijux-pollenomics-dev/src",
  "packages/bijux-pollenomics-dev/tests",
  "packages/pollenomics/src",
  "packages/pollenomics/tests",
]
exclude = [
  ".git",
  ".hg",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "artifacts",
  "build",
  "dist",
  "docs/report",
  "htmlcov",
  "__pycache__",
  "migrations",
  "node_modules",
  "*.egg-info",
  "site",
]
extend-exclude = ["data"]

[lint]
select = ["E", "F", "I", "B", "UP", "SIM", "C4", "PIE", "RET", "ISC"]
ignore = ["E501", "E203"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint.isort]
force-sort-within-sections = true
known-first-party = [
  "bijux_pollenomics",
  "bijux_pollenomics_dev",
  "pollenomics",
  "tests",
]

[lint.mccabe]
max-complexity = 10
