"""Analysis exports for harmonization, scoring, and reporting helpers."""

from .engine_manifest import (
    LakeSelectionRequirement,
    RankingEngineManifest,
    build_ranking_engine_manifest,
)
from .harmonization import HarmonizationRule, default_harmonization_rules
from .lake_evidence_richness import (
    DEFAULT_LAKE_EVIDENCE_RADII_KM,
    LakeEvidenceBandScore,
    LakeEvidenceCandidate,
    LakeEvidenceRichnessAssessment,
    LakeEvidenceRichnessReport,
    build_sweden_lake_evidence_richness_report,
)
from .ranking import (
    CandidateSensitivityReport,
    CandidateSensitivityRow,
    build_candidate_context,
    build_ranking_sensitivity_report,
    rank_localities,
    temporal_overlap,
)
from .review import (
    build_lake_evidence_richness_geojson,
    render_candidate_site_markdown,
    render_candidate_site_sensitivity_markdown,
    render_lake_evidence_richness_map_html,
    render_lake_evidence_richness_markdown,
    render_lake_evidence_richness_section,
    write_candidate_site_sensitivity_json,
    write_candidate_sites_csv,
    write_candidate_sites_json,
    write_lake_evidence_richness_band_csv,
    write_lake_evidence_richness_geojson,
    write_lake_evidence_richness_json,
    write_lake_evidence_richness_map_html,
    write_lake_evidence_richness_registry_csv,
    write_lake_evidence_richness_scenario_csv,
)
from .site_candidates import (
    CandidateRankingProfile,
    CandidateSiteContext,
    CandidateSiteScore,
    ScoringWeights,
    build_ranking_profiles,
    resolve_ranking_profile,
    score_candidate_site,
)

__all__ = [
    "CandidateRankingProfile",
    "CandidateSensitivityReport",
    "CandidateSensitivityRow",
    "DEFAULT_LAKE_EVIDENCE_RADII_KM",
    "HarmonizationRule",
    "LakeSelectionRequirement",
    "LakeEvidenceBandScore",
    "LakeEvidenceCandidate",
    "LakeEvidenceRichnessAssessment",
    "LakeEvidenceRichnessReport",
    "RankingEngineManifest",
    "build_candidate_context",
    "build_lake_evidence_richness_geojson",
    "build_ranking_engine_manifest",
    "build_ranking_profiles",
    "build_ranking_sensitivity_report",
    "build_sweden_lake_evidence_richness_report",
    "default_harmonization_rules",
    "CandidateSiteContext",
    "CandidateSiteScore",
    "rank_localities",
    "render_candidate_site_markdown",
    "render_candidate_site_sensitivity_markdown",
    "render_lake_evidence_richness_map_html",
    "render_lake_evidence_richness_markdown",
    "render_lake_evidence_richness_section",
    "resolve_ranking_profile",
    "ScoringWeights",
    "score_candidate_site",
    "temporal_overlap",
    "write_candidate_site_sensitivity_json",
    "write_candidate_sites_csv",
    "write_candidate_sites_json",
    "write_lake_evidence_richness_band_csv",
    "write_lake_evidence_richness_geojson",
    "write_lake_evidence_richness_json",
    "write_lake_evidence_richness_map_html",
    "write_lake_evidence_richness_registry_csv",
    "write_lake_evidence_richness_scenario_csv",
]
